### ISSUE TITLE
unable to interact with something

### ISSUE THREAD

**Issue by katabame** [SydneyMOD/SydneyHUD#100]
from @PoorPocketsMcNewHold on Discord,
unable to interact with something, The precedent version was working fine.

**Comment by PoorPocketsMcNewHold** [comment]
It's due to the InteractionExt.lua last commits, If I backup with the one from the old release, It works perfectly fine.

**Comment by KashEight** [comment]
Fixed @ this commit: [e60893f25a0322f7d08a5044d1e49954456992ff](https://github.com/SydneyMOD/SydneyHUD/commit/e60893f25a0322f7d08a5044d1e49954456992ff)

**Comment by PoorPocketsMcNewHold** [comment]
Can confirm, It fixed the issue.
