### ISSUE TITLE
Settings Constantly Resetting [Closed]

### ISSUE THREAD

**Issue by Silverbolt0953** [SydneyMOD/SydneyHUD#23]
When ever I am playing with SydneyHUD, I am forced to play with the default settings. When I change the settings, They reset to the default.

**Comment by katabame** [comment]
Is there any BLT logs?
the log located in `PAYDAY 2\mods\logs\`
maybe some file hash isn't matched.
try redownload and install?

**Comment by Silverbolt0953** [comment]
Well, I have found out that this is not a problem with SydneyHUD. It must be a problem with Payday 2 or BLT because my other mods such as Basic Voices or Carry Stacker Reloaded reset before, during, and after heists. This even happens after I reinstal. The also get renabled if I just disable them through the mod list in game.
