### ISSUE TITLE
Basic russian translation

### ISSUE THREAD

**Issue by exp1os1on** [SydneyMOD/SydneyHUD#34]
Something translation...

[russian.txt](https://github.com/SydneyMOD/SydneyHUD/files/1102945/russian.txt)
Rename to russian.json --> SydneyHUD/lang
SydneyHUD/menu/sydneyhud_options.lua add "language_russian"

**Comment by katabame** [comment]
`"flashlight_angle_desc": "Угол\ширина луча, 0-160 (по умол. 60)",` (line 95) has Invalid escape character.
Can I change the `\` to `/` ?

**Comment by exp1os1on** [comment]
"flashlight_angle_desc": "Угол луча, 0-160 (по умол. 60)"
it will be better

**Comment by katabame** [comment]
Added your translation at 6a37aa6ce572ba675f95071bbd8b3fa07005ada8!
Thanks for your submitting.

_(We recommended **[PullRequest](https://help.github.com/articles/about-pull-requests/)** for submit codes. But if you aren't good at it, open issue like this!)_
