### ISSUE TITLE
Sentry AP Crash

### ISSUE THREAD

**Issue by tiduseQ** [SydneyMOD/SydneyHUD#38]
Hello. I'm using newest version (3.0.1 is it?) and the game still crashes when sentry is placed. Last game it allowed me to put 4 sentries, then i picked one and game crashed after replacing. Next games it crashes after placing first one.

Below I'll paste crash logs:

Wed Jun 28 10:44:08 2017

Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1034               
                _send_queued()  lib/network/base/networkpeer.lua:1072               
            send_queued_sync()  lib/network/base/networkpeer.lua:1094               
       send_to_peers_synched()  lib/network/base/basenetworksession.lua:687         
                                @mods/SydneyHUD/lua/SentryGunWeapon.lua:28          
                            ()  =(tail                                              
                      call):-1  _update_queued_tasks()                              
lib/managers/enemymanager.lua:580  update()                                            
lib/managers/enemymanager.lua:48                                                      
  lib/setups/gamesetup.lua:651  ()                                                  
                        =(tail  call):-1                                            
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------
System information:
	Application version : 1.72.257
	CPU : Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 10.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvd3dum.dll[21.21.13.7595]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8191MB 56KB
	OS : 6.1.7601 (Service Pack 1) 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (Siberia Raw Prism Headset))
----------------------------------------------------------------------
Wed Jun 28 10:53:45 2017
Application has crashed: access violation
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
-------------------------------
Current thread: Main
Script stack:
                        send()  lib/network/base/networkpeer.lua:1034               
                _send_queued()  lib/network/base/networkpeer.lua:1072               
            send_queued_sync()  lib/network/base/networkpeer.lua:1094               
       send_to_peers_synched()  lib/network/base/basenetworksession.lua:687         
                                @mods/SydneyHUD/lua/SentryGunWeapon.lua:28          
                            ()  =(tail                                              
                      call):-1  _update_queued_tasks()                              
lib/managers/enemymanager.lua:580  update()                                            
lib/managers/enemymanager.lua:48                                                      
  lib/setups/gamesetup.lua:651  ()                                                  
                        =(tail  call):-1                                            
                      update()  lib/setups/networkgamesetup.lua:21                  
                                core/lib/setups/coresetup.lua:537                   
                            ()  =(tail                                              
                      call):-1  
-------------------------------
System information:
<<<same as above)>>>

**Comment by katabame** [comment]
Hello, @tiduseQ .
`Application has crashed: access violation`
This line means That crash happened by PAYDAY2 side.
We can't fix this.
