### ISSUE TITLE
Crash issue with auto AP round on sentry

### ISSUE THREAD

**Issue by Bekabeshechka** [SydneyMOD/SydneyHUD#42]
Have just tried Sydneyhud 
using Valky rifle China puff 
Playing on Safe house raid overkill + deathwish for solo and got disconnected after other joined my host
I'm using 6 sentry gun, 4 suppressed and 2 normal
Look okay when i was alone and got crash after someone joined (at 100%) , i dont alway get crash right away when someone joined but most of time , someone joined and i crashed, ocasionally i can play a bit few second to almost a minute after 1 or 2 players joined at most
There were no other mod but BLT and Sydneyhud
Also when i turned off auto AP round for sentry, it's fixed, no more crash with the same setup and players joining back and forth 
i really love your hud , i hope you can fix it in some way or make a seperate mod for sentry auto AP that work without crashing

[crash.txt](https://github.com/SydneyMOD/SydneyHUD/files/1116003/crash.txt)

**Comment by PoorPocketsMcNewHold** [comment]
Application has crashed: access violation is a Payday 2 bug. Not a bug with SydneyHUD itself.
We can't do stuff about it.
