### ISSUE TITLE
Anti Desync feature related crash?

### ISSUE THREAD

**Issue by elnino97** [SydneyMOD/SydneyHUD#48]
I had a crash yesterday when a player went into custody. Looked in the crashlog and saw this. Could this be related to the anti desync feature in the mod?

Application has crashed: C++ exception
[string "lib/units/beings/player/huskplayermovement...."]:3661: attempt to index field '_magazine_data' (a nil value)

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.74.275.
	CPU : Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 10.0 
	GPU : Intel(R) HD Graphics 3000 / nvumdshim.dll[21.21.13.7892]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     10145MB 60KB
	OS : 6.1.7601 (Service Pack 1) 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by PoorPocketsMcNewHold** [comment]
We released a Quick-fix yesterday about that. Did you get this crash before or after this quick update?

**Comment by elnino97** [comment]
Thanks for responding. I used the version from paydaymods so I'm guessing it's before the update. I'll try installing the github version.

**Comment by PoorPocketsMcNewHold** [comment]
Pretty much don't. Launch your game, And if you don't have any Pop-up messages asking you to update the mod, It's that you got the latest version. The Quick-fix has been launched at ~14:32 GMT+1.

**Comment by katabame** [comment]
Sorry for very late responding.
```
Application has crashed: C++ exception
[string "lib/units/beings/player/huskplayermovement...."]:3661: attempt to index field '_magazine_data' (a nil value)
```
maybe other player still installed AntiDesync mod, and it caused strange packet.
We can't do any stuff for that. Sorry.
