### ISSUE TITLE
[Highest Priority] Make compatibility to BLT2

### ISSUE THREAD

**Issue by katabame** [SydneyMOD/SydneyHUD#60]
PAYDAY2 is updated to add support for LuaJIT. thanks to it, BLT is updated to BLT2.
Some of methods is outdated, SydneyHUD won't launch up anymore.
maybe need rewrite bunch of codes, time to update to SydneyHUD v4.

**Comment by KashEight** [comment]
Probably, outdated methods will be disabled.
I consinder the new way to solve it. (it is my opinion, so I do not support it is correct.)
# MenuHelper
Make and use .json files instead of using the MenuHelper function.
.json file-details is written next Localization.

# Localization
*I do not have the instead idea yet, sorry.*

# Json Menus
Make and definition the new .json files that support SydneyHUD's menu.

**Comment by katabame** [comment]
To see latest version of payday2 luajit files, see: [BitBucket/TdlQ/payday-2-luajit](https://bitbucket.org/TdlQ/payday-2-luajit/src)
(thanks NewHold for letting me know)

**Comment by katabame** [comment]
And those pages are will helpful.
[Payday 2: You're crashing with the new U153 and BLT 2.0?
 :: ModWorkShop](https://modworkshop.net/showthread.php?tid=7275)
[How to "Update" Mods To Their New Forms? :: Reddit](https://www.reddit.com/r/paydaytheheistmods/comments/6xa7r8/how_to_update_mods_to_their_new_forms/dmeguj8/)
[[Tutorial] How to update your basic LUA mods to BLT V2 :: Reddit](https://www.reddit.com/r/paydaytheheistmods/comments/6xbpu9/tutorial_how_to_update_your_basic_lua_mods_to_blt/)

**Comment by katabame** [comment]
Reference: [JamesWilko/Payday-2-BLT/#97](https://github.com/JamesWilko/Payday-2-BLT/issues/97)

**Comment by katabame** [comment]
Bug report from Twitter user.
```
Mon Sep 04 11:14:37 2017


Application has crashed: C++ exception
mods/SydneyHUD-master/lua/ChatManager.lua:108: attempt to index global 'DelayedCallsFix' (a nil value)



SCRIPT STACK

init() @mods/SydneyHUD-master/lua/ChatManager.lua:33
new() core/lib/utils/coreclass.lua:35
add_game_chat() lib/managers/menu/menucomponentmanager.lua:2427
create() lib/managers/menu/menucomponentmanager.lua:2347
set_active_components() lib/managers/menu/menucomponentmanager.lua:429
set_active_components() @mods/base/lua/MenuComponentManager.lua:19
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.326.
	CPU : Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 3GB / nvldumd.dll[22.21.13.8494]
	Language : @ID94cca2fdaccfc2cd@
	Memory :     8137MB 988KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : NVIDIA Corporation (BenQ M2700HD-0 (NVIDIA High Definition Audio))



----------------------------------------------------------------------
```

Source: https://twitter.com/choco_colonel/status/904680870040150016

**Comment by katabame** [comment]
some of user reported issue w/ DelayedCallsFix. SydneyHUD should be include codes of them. I'm working on.

**Comment by katabame** [comment]
some of user reported issue w/ DelayedCallsFix. SydneyHUD should be include codes of them. I'm working on.

**Comment by katabame** [comment]
almost stable. we can release v4.0-stable, isn't it?

**Comment by katabame** [comment]
@kash planning any modification  or not?

**Comment by katabame** [comment]
@KashEight planning any modification or not?

**Comment by katabame** [comment]
v4.0.0 stable is now released.
