### ISSUE TITLE
"Remove" the language selection button.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [SydneyMOD/SydneyHUD#63]
Since the new BLT 2 hook adds a language selection thingy in the mod options already, I suggest that we should remove the one directly in the SydneyHUD mod options. That's a small detail that probably everybody will ignore... Except me.

**Comment by katabame** [comment]
![image](https://user-images.githubusercontent.com/9818101/31062045-7d44037a-a762-11e7-8ba6-5f8a99ac35c4.png)
you meant this option, right?
this option for BLT2, I don't want interrupt this value.

**Comment by PoorPocketsMcNewHold** [comment]
Exactly, this option. Well, In this case, you can close the issue.
