### ISSUE TITLE
crash when playing online or creating a lobby

### ISSUE THREAD

**Issue by PKSHFUCKME** [SydneyMOD/SydneyHUD#64]
like the title says i can play offline but whenever i create  a lobby i crash

**Comment by PoorPocketsMcNewHold** [comment]
Your crashlog would be useful.
It's situated in your C:\Users\USERNAME\AppData\Local\PAYDAY 2 folder and it's named crashlog.txt
Only the last crash test who begin with the time when you crashed the last time while playing online is interesting, but if you are lazy, you can directly give us the crashlog.txt file directly.

**Comment by KashEight** [comment]
I fixed it and download new one from here:
https://github.com/SydneyMOD/SydneyHUD/releases/tag/4.0.0-pre2
