### ISSUE TITLE
pre2に更新後起動するとクラッシュ

### ISSUE THREAD

**Issue by tukishimalight** [SydneyMOD/SydneyHUD#65]
本題どうりpre2に更新すると起動時にクラッシュしてメニュー画面にすらたどり着けません。pre1に戻すと起動できたのでpre2に問題があるのではと思います。

**Comment by PoorPocketsMcNewHold** [comment]
> 詳細文の最後にクラッシュログを貼り付けてください。
最新のクラッシュログは"%localAppdata%\PAYDAY 2\crash.txt"で確認できます。

**Comment by KashEight** [comment]
修正しましたのでこちらから新しいものをダウンロードしてください。
https://github.com/SydneyMOD/SydneyHUD/releases/tag/4.0.0-pre2
