### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by VictorHachard** [SydneyMOD/SydneyHUD#66]
game crash when i start it. I update to btl 2.0 and all me mod is working but not the HUB. Nice mod and good luck for the fix.

**Comment by PoorPocketsMcNewHold** [comment]
Could you give us the crashlog of the crash? It's situated in your C:\Users\USERNAME\AppData\Local\PAYDAY 2 folder. And only the last part, at the exact date when your game crashed are interesting for us.
_If you are lazy, You can just give us the crash.txt file directly._

**Comment by Pinti-pnda** [comment]
poorpocketsmcnewhold 
[crash.txt](https://github.com/SydneyMOD/SydneyHUD/files/1276829/crash.txt)
[crashlog.txt](https://github.com/SydneyMOD/SydneyHUD/files/1276830/crashlog.txt)

**Comment by KashEight** [comment]
I fixed it and download new one from here:
https://github.com/SydneyMOD/SydneyHUD/releases/tag/4.0.0-pre2

**Comment by VictorHachard** [comment]
[crash.txt](https://github.com/SydneyMOD/SydneyHUD/files/1278747/crash.txt)
[crashlog.txt](https://github.com/SydneyMOD/SydneyHUD/files/1278746/crashlog.txt)
There is the file, thank for the answer and i test the 4.0.0-pre2 not working for me.
