### ISSUE TITLE
Pre2でSTART THE HEISTボタンを押すとクラッシュ

### ISSUE THREAD

**Issue by AquaGreen** [SydneyMOD/SydneyHUD#67]
JOBを開始するときのボタンであるSTART THE HEISTをクリック後、JOBに入れずにそのままクラッシュしてしまいます。他に入れていたmodを抜いても同じ現象が起きるため、他のmodと干渉ではなさそうです。よろしくお願いします。
[crash.txt](https://github.com/SydneyMOD/SydneyHUD/files/1278283/crash.txt)
[crashlog.txt](https://github.com/SydneyMOD/SydneyHUD/files/1278284/crashlog.txt)

**Comment by katabame** [comment]
ご報告ありがとうございます。
どうもpre-2で追加した機能が上手く動作していないために発生するようです。
修正に努めますが、修正されるまでの間は
恐らく`DelayedCallsFix`を導入した状態で`pre-1`に差し戻すと正常に動作いたします。
お手数をお掛けいたしますがお試しいただけますようお願い致します。
