### ISSUE TITLE
AccessViolation crash caused by SydneyHUD:DelayedCalls functions

### ISSUE THREAD

**Issue by katabame** [SydneyMOD/SydneyHUD#68]
some of user already reported, SydneyHUD:DelayedCalls is not working well I think.
Must be re-check and re-write. or just revert to pre-1 with installing original DelayedCallsFix.

**Comment by katabame** [comment]
Reference: #60

**Comment by KashEight** [comment]
I fixed it in this commit: [27fbcdd33925d95c1d66694b0aa9fd1fe35ecd95](https://github.com/SydneyMOD/SydneyHUD/commit/27fbcdd33925d95c1d66694b0aa9fd1fe35ecd95)
