### ISSUE TITLE
game crach at start

### ISSUE THREAD

**Issue by VictorHachard** [SydneyMOD/SydneyHUD#70]
hi there is the issuse

12:35:48 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED
12:36:34 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:36:36 AM Log:  (..\src\http\http.cpp:44) CURL_INITD
12:36:36 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:36:36 AM Lua: [BLT] Setup...
12:36:36 AM Lua: [BLT] Loading module: 	BLTLogs
12:36:36 AM Lua: [BLT] Loading module: 	BLTModManager
12:36:36 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:36:36 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:36:36 AM Lua: [BLT] Loading module: 	BLTLocalization
12:36:36 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:36:36 AM Lua: [BLT] Loading mods for state: table: 0x001d0660
12:36:36 AM Lua: [BLT] Loading mod: base
12:36:36 AM Lua: [BLT] Loading mod: SydneyHUD-master
12:36:37 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:36:37 AM Lua: [BLT] Setting up mod: 	base
12:36:37 AM Lua: [BLT] Setting up mod: 	SydneyHUD-master
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind save_pre]
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind load_pre]
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind check_ping]
12:36:37 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:36:37 AM Lua: [BLT] Setup...
12:36:37 AM Lua: [BLT] Loading module: 	BLTLogs
12:36:37 AM Lua: [BLT] Loading module: 	BLTModManager
12:36:37 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:36:37 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:36:37 AM Lua: [BLT] Loading module: 	BLTLocalization
12:36:37 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:36:37 AM Lua: [BLT] Loading mods for state: table: 0x001d0640
12:36:37 AM Lua: [BLT] Loading mod: base
12:36:37 AM Lua: [BLT] Loading mod: SydneyHUD-master
12:36:37 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:36:37 AM Lua: [BLT] Setting up mod: 	base
12:36:37 AM Lua: [BLT] Setting up mod: 	SydneyHUD-master
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind save_pre]
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind load_pre]
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind check_ping]
12:36:37 AM Lua: [SydneyHUD Info] SydneyHUD loaded.
12:36:37 AM Lua: [SydneyHUD Warn] unlinked script called: lib/setups/menusetup
12:36:37 AM Log:  (..\src\InitiateState.cpp:659) Initiating Hook
12:36:37 AM Lua: [BLT] Setup...
12:36:37 AM Lua: [BLT] Loading module: 	BLTLogs
12:36:37 AM Lua: [BLT] Loading module: 	BLTModManager
12:36:37 AM Lua: [BLT] Loading module: 	BLTKeybindsManager
12:36:37 AM Lua: [BLT] Loading module: 	BLTPersistScripts
12:36:37 AM Lua: [BLT] Loading module: 	BLTLocalization
12:36:37 AM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
12:36:37 AM Lua: [BLT] Loading mods for state: table: 0x23361480
12:36:37 AM Lua: [BLT] Loading mod: base
12:36:37 AM Lua: [BLT] Loading mod: SydneyHUD-master
12:36:37 AM Lua: [] Could not load file 'mods/saves/blt_data.txt', no data loaded...
12:36:37 AM Lua: [BLT] Setting up mod: 	base
12:36:37 AM Lua: [BLT] Setting up mod: 	SydneyHUD-master
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind save_pre]
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind load_pre]
12:36:37 AM Lua: [Keybind] Registered keybind [BLTKeybind check_ping]
12:36:38 AM Lua: [SydneyHUD Info] language: english.json
12:36:38 AM Lua: [Error] Could not load file: mods/SydneyHUD-master/menu/sydneyhud_hud_lists_options_buffs.json
12:36:45 AM Log:  (..\src\http\http.cpp:49) CURL CLOSED

**Comment by katabame** [comment]
Hi, thanks for reporting.
But here is simple 2 questions.

1: what's version of SydneyHUD you use?
2: Can we see crashlog that located at `C:\Users\USERNAME\AppData\Local\PAYDAY 2\crashlog.txt`?

**Comment by VictorHachard** [comment]
The last one and i reinstal the game, BLT 2.0.

Application has crashed: C++ exception
mods/SydneyHUD-master/SydneyHUD.lua:375: attempt to index local 'mod' (a nil value)



SCRIPT STACK

_add_version_string_original() @mods/SydneyHUD-master/lua/MenuNodeGui.lua:7
_add_version_string() @mods/SydneyHUD-master/lua/MenuNodeGui.lua:6
_setup_item_rows_original() lib/managers/menu/menunodegui.lua:1771
_setup_item_rows_original() @mods/SydneyHUD-master/lua/MenuNodeGui.lua:14
_setup_item_rows() @mods/SydneyHUD-master/lua/MenuNodeGui.lua:14
init() core/lib/managers/menu/reference_renderer/coremenunodegui.lua:64
init() lib/managers/menu/menunodegui.lua:68
new() core/lib/utils/coreclass.lua:35
show_node() core/lib/managers/menu/reference_renderer/coremenurenderer.lua:81
lib/managers/menu/menurenderer.lua:63
_call_callback() core/lib/managers/menu/coremenulogic.lua:329
core/lib/managers/menu/coremenulogic.lua:96
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:159
update() lib/managers/menumanagerpd2.lua:17
update() lib/setups/setup.lua:740
update() lib/setups/menusetup.lua:294
update() @mods/base/lua/MenuSetup.lua:6
core/lib/setups/coresetup.lua:537


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.76.327.
	CPU : Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 970 / nvd3dum.dll[21.21.13.7653]
	Language : @IDaadeda58d8e5a71d@
	Memory :     16077MB 884KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Haut-parleurs (Périphérique High Definition Audio))

Thanks

**Comment by katabame** [comment]
Thanks for responding, We're digging about it.

**Comment by katabame** [comment]
@Glaskani
Could you try rename your `SydneyHUD-master` folder to `SydneyHUD`?

**Comment by VictorHachard** [comment]
After rename the folder it work, i m felling stupid.
Thanks for the help and nice work.

**Comment by katabame** [comment]
Thanks for testing it too, we're taking note about it.
