### ISSUE TITLE
Sound & Music Sliders issues. 

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [SydneyMOD/SydneyHUD#77]
Reported by Django on our [Steam Group](http://steamcommunity.com/groups/SydneyMOD/discussions/6/1519260397785562094/).

> The sound & music slider, can only be modified, by multiple of 10 (0,10,20,etc..)
> When trying to set a precise value, like you did. The game simply put the closest multiple of 10 value (For a value, set to 3, The game will switch to the closest multiple of 10 value which is 0%).

https://thumbs.gfycat.com/AgitatedIllinformedBonobo-size_restricted.gif

**Comment by katabame** [comment]
In my test case, the slider value window is not poping out. Is that provided by any mod?

**Comment by PoorPocketsMcNewHold** [comment]
I've tested with Beardlib enabled, Since I wanted to test this issue rapidly but I'm pretty sure that it doesn't add this thing, especially when this feature doesn't work when SydneyHUD is disabled. 
Right click on the slider to pop that out.

**Comment by katabame** [comment]
4c628c0 will fix this issue.
