### ISSUE TITLE
copdamage.lua got nil value

### ISSUE THREAD

**Issue by katabame** [SydneyMOD/SydneyHUD#8]
Occurred job: `Watch Dogs OneDown Day1`

Description:
Crash suddenly all latest SydneyHUD users same time.
Disabled `Show Minion`, but still crashing. Maybe `Kill counter` or like that?

Local commit: 415f896ef873e29afa47d30afcdb9f4883e3a123
Occurred PAYDAY2 Version: `130.0` and `130.1`

Crash log:
```
Application has crashed: C++ exception
[string "lib/units/enemies/cop/copdamage.lua"]:2423: attempt to index a nil value

SCRIPT STACK
-------------------------------
Callstack:
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlReAllocateHeap                                   
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
-------------------------------
Current thread: Main
-------------------------------
```

**Comment by BangL** [comment]
"lib/units/enemies/cop/copdamage.lua" means its the payday2 file, not ours.
otherwise it would be like "mods/SydneyHUD/lua/CopDamage.lua"
the line reference is misleading in this case.

can be anything, also another mod or the game itself.

**Comment by BangL** [comment]
..oh you actually referenced the decompiled file from DrNewbie, didnt see that before.
anyways: the decompiled versions dont have the exact same line numbers as the actual game. it can be another line where it happened.

**Comment by katabame** [comment]
I deleted the reference link...

`lib/units/enemies/cop/copdamage.lua` hooked by [mod.txt line79](https://github.com/SydneyMOD/SydneyHUD/blob/master/mod.txt#L79) and [SydneyHUD.lua line118](https://github.com/SydneyMOD/SydneyHUD/blob/master/SydneyHUD.lua#L118).

Occurring those hooks or vanilla payday2 issue I think... idk which is cause

**Comment by katabame** [comment]
I'll try commenting out the hook line to decide which is cause after I back to home.

**Comment by BangL** [comment]
it is like looking for a needle in a haystack.
you can play for ages without having this issue, and sometimes it happens. but super rare. almost impossible to reproduce.

**Comment by katabame** [comment]
it happened continuous 3times or more.
but yea, it probably happened by vanilla payday2...

**Comment by BangL** [comment]
..or by corrupt network data by another client. i played today with some friends.. no problems at all. also on watchdogs one down.
therefore the problem is sporadic.
