### ISSUE TITLE
One down now @ 3 downs for Beta users

### ISSUE THREAD

**Issue by ghost** [SydneyMOD/SydneyHUD#91]
For the Sniper Beta users like me, I noticed that the chat info for the times down will still display 0/2 (for aced nine lives) and 0/1 (non~aced nine lives) on One Down even though the downs have been upped to default 3 downs w/o nine lives and 4 downs w/nine lives.
Anything we can do to fix this tiny issue?

**Comment by katabame** [comment]
Hi Noxxyy!

Could you try following steps?
1. Open `SydneyHUD.lua` with your favorite editor.
1. Delete [Line460~Line462](https://github.com/SydneyMOD/SydneyHUD/blob/master/SydneyHUD.lua#L460-L462)
1. Toggle off automatic update for SydneyHUD in BLT mod manager.
1. Then start any heist.

I hope this solution will fix your issue.

**Comment by KashEight** [comment]
Fixed @ this commit: [b0b783dfe62ad4d7da6ee1574fd864980e104c72](https://github.com/SydneyMOD/SydneyHUD/commit/b0b783dfe62ad4d7da6ee1574fd864980e104c72)
