### ISSUE TITLE
Add Portuguese localization in language selection

### ISSUE THREAD

**Issue by Kazenin** [SydneyMOD/SydneyHUD#95]
Please, add portuguese in language selector

![captura de tela de 2018-03-15 18-00-36](https://user-images.githubusercontent.com/9669576/37495382-f8b92d2a-287a-11e8-9b9c-929077397f05.png)

**Comment by Kazenin** [comment]
I fixed and submit a [pull request ](https://github.com/SydneyMOD/SydneyHUD/pull/94)

**Comment by katabame** [comment]
Reference: #94
