### ISSUE TITLE
Wrong names in enemy health bar

### ISSUE THREAD

**Issue by Kazenin** [SydneyMOD/SydneyHUD#99]
Please, fix these enemies names in that feature:

From `tank_mini` to `Minigun Bulldozer`
From `tank_medic` to `Medic Bulldozer`

See a picture with this issue:

![20180317020619_1](https://user-images.githubusercontent.com/9669576/37552005-5a9da340-297a-11e8-8dd1-461c0186d592.jpg)

**Comment by KashEight** [comment]
Fixed @ this commit: [925346044e4a2066235ae74681853df43ace2383](https://github.com/SydneyMOD/SydneyHUD/commit/925346044e4a2066235ae74681853df43ace2383)
